version: '2'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile-api.prod
    ports:
      - "3000:3000"
    links:
      - db
    command: yarn run start-dev
  web:
    build:
      context: .
      dockerfile: Dockerfile-web.prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    command: node server.js

volumes:
  pgdata:
