version: '2'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "5432:5432"
    volumes:
      - ./db-dev:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile-api.dev
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    command: yarn run start-dev
  web:
    build:
      context: .
      dockerfile: Dockerfile-web.dev
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
    command: yarn start
